### ISSUE TITLE
Invalid parameters.

### ISSUE THREAD

**Issue by Thijxx** [arsenlosenko/python-ripple-rpc#1]
The Account transaction example seems to be flawed. The message` "Invalid parameters."` is all it will produce. I have tried multi servers and multiple account.
Also, the `amount` must be a _string_ if I read this correctly in the `send_xrp` function.

**Comment by arsenlosenko** [comment]
Oh, my bad, I forgot that I tested it only with my local rippled instance (using port 5005), and didn't change the host. You can test it using credentials from [Testnet Faucet](https://developers.ripple.com/xrp-test-net-faucet.html). I updated the readme. 
Yes, amount must be a string, but in case with `send_xrp` amount could be any type, it will be converted to string after encoding into json.

**Comment by dvilelaf** [comment]
I'm also having the same issue. Connected to https://s.altnet.rippletest.net:51234, and wheter I use a string or a float for `amount`, I get the `invalidParams` error.

**Comment by arsenlosenko** [comment]
All right, it seems I have fixed it. Please update the package (with ```pip install --upgrade python-ripple-lib```) and try again, but for `send_xrp` method please connect to local node, or node which has an option of signing transactions (https://s.altnet.rippletest.net:51234/ doesn't have that). 
If issue still remains respond here.
Thanks!

**Comment by dvilelaf** [comment]
So, do I have to be running a node? Is there any testnet node capable of signing?

**Comment by arsenlosenko** [comment]
For now I don't know is there any testnet node capable of signing, I tested it on my local node
