### ISSUE TITLE
Add link to new Ripple xrpl-py library

### ISSUE THREAD

**Issue by hammertoe** [arsenlosenko/python-ripple-rpc#13]
Hi Arsen,
 I don't know if you saw, but recently Ripple released an 'official' XRPL python library hosted at the XRP Ledger Foundation's github:

https://pypi.org/project/xrpl-py/
https://github.com/XRPLF/xrpl-py

I noticed your library hasn't been updated in a number of years, and was wondering if you are still maintaining it? Would you be interested in putting a link in your README to xrpl-py which is under active maintenance? I'm happy to submit a PR for this to your repo, but wanted to ask first!

Thanks,
Matt

**Comment by arsenlosenko** [comment]
Hello Matt!

Currently I am not maintaining this library, only exception is review of incoming PRs and update of the library on PyPI after PRs are merged, so considering that, it would be way nicer if people would switch to 'official' library which is actively maintained. I will edit the README so it would include links to that library.
Thanks for reaching out!

**Comment by arsenlosenko** [comment]
Links to the library were placed on top of README file

**Comment by hammertoe** [comment]
Fantastic, thank you Arsen! :)
