### ISSUE TITLE
Parameters of RippleDataAPIClient functions are not used

### ISSUE THREAD

**Issue by jcperkins12** [arsenlosenko/python-ripple-rpc#9]
## Problem
The Ripple Data API server is not applying the parameters of the RippleDataAPIClient functions

## Context
I run a script using this code every day and the the code seemed to be working fine until 2/19/2020. 
* If I submit the same information using the Requests module with the parameters packaged under the 'data' argument of Requests(), then the parameters are not applied. 
* If I submit the request with the parameters encoded into the URL then the parameters are correctly applied in the ripple data api server.

My environment:
  `Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32 `

## Example
Data request using the Data API v2 Tool provided by Ripple [https://xrpl.org/data-api-v2-tool.html#get-account-value-stats] (https://xrpl.org/data-api-v2-tool.html#get-account-value-stats)

URL:
```
https://data.ripple.com/v2/accounts/rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn/stats/value?limit=2&descending=true&start=2020-02-20T01:00:00Z
```
Response:
```
{
  "result": "success",
  "count": 2,
  "marker": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn|20200229000000",
  "rows": [
    {
      "date": "2020-03-02T00:00:00Z",
      "account_value": "423.0136879999998",
      "balance_change_count": 0
    },
    {
      "date": "2020-03-01T00:00:00Z",
      "account_value": "423.0136879999957",
      "balance_change_count": 0
    }
  ]
}
```

When I try the equivalent request with the RippleDataAPIClient:
```python
>>> import pandas as pd
>>> from ripple_api import RippleDataAPIClient
>>> ts = pd.Timestamp("2020-02-20 01:00:00").strftime("%Y-%m-%dT%H:%M:%SZ")
>>> ts
'2020-02-20T01:00:00Z'
>>> acct = "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn"
>>> api = RippleDataAPIClient("https://data.ripple.com")
>>> api.get_account_value_stats(acct, start=ts, limit=2, descending=True)
```
Response:
```
{'result': 'success',
 'count': 200,
 'marker': 'rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn|20141215000000',
 'rows': [{'date': '2014-05-29T00:00:00Z',
   'account_value': '100.0',
   'balance_change_count': 1},
  {'date': '2014-05-30T00:00:00Z',
   'account_value': '100.0',
   'balance_change_count': 0},
  {'date': '2014-05-31T00:00:00Z',
   'account_value': '100.0',
   'balance_change_count': 0},
  {'date': '2014-06-01T00:00:00Z',
   'account_value': '100.0',
   'balance_change_count': 0},
    ... for 196 more records
```

**Comment by arsenlosenko** [comment]
Hello!
Thanks for the detailed overview of the issue (and the PR you have submitted), I'll review it and update the package on PyPI

**Comment by arsenlosenko** [comment]
Thanks for the PR, I have updated the package, here it is on PyPI:
https://pypi.org/project/python-ripple-lib/1.0.8/
If anything is wrong after the update feel free to reopen this issue (or open a new one). 
Have a nice day!
